version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../ops/Dockerfile.frontend
    environment:
      - PUBLIC_BASE_PATH=/doodle-td
      - VITE_API_BASE=/doodle-td-api
    volumes:
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: ../ops/Dockerfile.backend
    environment:
      - NODE_ENV=production
      - PORT=51502
      - HOST=0.0.0.0
      - DATABASE_URL=postgres://app:app@db:5432/doodletd
      - JWT_SECRET=${JWT_SECRET:-change-me-in-production}
      - REFRESH_SECRET=${REFRESH_SECRET:-change-me-in-production}
      - RATE_LIMIT_MAX=100
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:51502/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=doodletd
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d doodletd"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/doodle-td/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  frontend_dist: