version: '3.8'

services:
  frontend:
    build: ./frontend
    environment:
      - PUBLIC_BASE_PATH=/doodle-td
      - VITE_API_BASE=/doodle-td-api
    volumes:
      - frontend_dist:/app/dist

  backend:
    build: ./backend
    environment:
      - NODE_ENV=development
      - PORT=51502
      - HOST=0.0.0.0
      - DATABASE_URL=postgres://app:app@db:5432/doodletd
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - RATE_LIMIT_MAX=100
    ports:
      - "127.0.0.1:51502:51502"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=doodletd
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d doodletd"]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  frontend_dist: